version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    network_mode: host
#    ports:
#      - "27017:27017"
    volumes:
      - ./db:/data/db:rw
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  jaqpot-api:
    depends_on: [mongo]
    image: upcintua/jaqpot-api:5.0.45
    network_mode: host
#    ports:
#      - "8080:8080"
    environment:
      JAQPOT_DB_CONNECTION_STRING: mongodb://root:example@localhost:27017

  quots:
    depends_on: [mongo]
    image: upcintua/quots
    network_mode: host
#    ports:
#      - "8000:8000"
    environment:
      MONGO_URL: mongodb://root:example@localhost:27017

  generic-r:
    depends_on: [mongo]
    network_mode: host
    image: upcintua/jpdi-r:1.1.9
#    ports:
#      - "8004:8004"

